server:
  port: 8081
spring:
  application:
      name: spring-boot-test

  # Logback
  log:
    file:
      path: ${HOME}/logs/${spring.application.name}/${spring.profiles.active} # 日志文件路径
      maxKeep: 5  # 最大保留的文件个数

# ES
  data:
    elasticsearch:
      # 集群名
      cluster-name: es-baili
      # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
      cluster-nodes: localhost:9300
      # 是否本地连接
      local: false
      repositories:
        # 仓库中数据存储
        enabled: true